api_platform:
    title: "CoachZone API"
    version: "1.0.0"
    description: "API pour mettre en relation des coachs sportifs avec des institutions"
    formats:
        json: ["application/json"]
    error_formats:
        json: ["application/json"]
    defaults:
        stateless: false
        formats: ["json"]
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]

    # Configuration pour la documentation
    enable_swagger_ui: true
    enable_re_doc: true
