api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        json: ["application/json"]
        jsonld: []
    defaults:
        stateless: true
        formats: ["json"]
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
