symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 3600  # Token valid for 1 hour (3600 seconds)
    throttle_limit: 3600  # Throttle requests for 1 hour
