import { StyleSheet } from "react-native";
export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#f5f5f5",
    },
    scrollView: {
        flex: 1,
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        padding: 16,
        backgroundColor: "#fff",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    backButton: {
        marginRight: 16,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: "600",
        color: "#333",
    },
    placeInfo: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        padding: 16,
        marginBottom: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
    },
    placeName: {
        fontSize: 16,
        fontWeight: "600",
        marginLeft: 10,
        marginRight: 10,
        color: "#333",
    },
    section: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 16,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "600",
        marginBottom: 16,
        color: "#333",
    },
    instructionText: {
        fontSize: 14,
        color: "#555",
        marginBottom: 16,
        fontStyle: "italic",
    },
    noDateSelectedText: {
        fontSize: 14,
        color: "#888",
        fontStyle: "italic",
        textAlign: "center",
        padding: 20,
    },
    timeSlotsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        justifyContent: "flex-start",
        gap: 10,
    },
    timeSlot: {
        paddingVertical: 10,
        paddingHorizontal: 14,
        borderRadius: 8,
        backgroundColor: "#f0f0f0",
        borderWidth: 1,
        borderColor: "#ddd",
        minWidth: "30%",
        alignItems: "center",
        marginBottom: 10,
    },
    timeSlotText: {
        fontSize: 14,
        color: "#333",
    },
    selectedTimeSlot: {
        backgroundColor: "#007AFF",
        borderColor: "#007AFF",
    },
    selectedTimeSlotText: {
        color: "#fff",
        fontWeight: "600",
    },
    showMoreButton: {
        alignSelf: "center",
        marginTop: 16,
        paddingVertical: 8,
        paddingHorizontal: 16,
        backgroundColor: "#f0f0f0",
        borderRadius: 20,
    },
    showMoreButtonText: {
        fontSize: 14,
        color: "#007AFF",
        fontWeight: "500",
    },
    priceContainer: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingVertical: 10,
    },
    priceText: {
        fontSize: 14,
        color: "#555",
    },
    priceValue: {
        fontSize: 18,
        fontWeight: "bold",
        color: "#28a745",
    },
    priceInfo: {
        fontSize: 12,
        color: "#777",
        fontStyle: "italic",
        marginTop: 10,
    },
    summaryContainer: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 16,
        marginHorizontal: 16,
        marginBottom: 24,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    summaryTitle: {
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 16,
        color: "#333",
        textAlign: "center",
    },
    summaryItem: {
        flexDirection: "row",
        marginBottom: 8,
    },
    summaryLabel: {
        width: 100,
        fontSize: 14,
        fontWeight: "600",
        color: "#555",
    },
    summaryValue: {
        flex: 1,
        fontSize: 14,
        color: "#333",
    },
    submitButton: {
        backgroundColor: "#28a745",
        padding: 16,
        borderRadius: 12,
        marginHorizontal: 16,
        marginBottom: 32,
        alignItems: "center",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1.5,
    },
    disabledButton: {
        backgroundColor: "#a0c7a9",
    },
    submitButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
});
