import { StyleSheet } from "react-native";
export default StyleSheet.create({
    container: {
        flexDirection: "row",
        marginBottom: 16,
        alignItems: "center",
    },
    searchContainer: {
        flex: 1,
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "white",
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        color: "#333",
    },
    filterButton: {
        marginLeft: 12,
        paddingHorizontal: 12,
        height: 40,
        borderRadius: 20,
        backgroundColor: "white",
        alignItems: "center",
        justifyContent: "center",
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    filterButtonContent: {
        flexDirection: "row",
        alignItems: "center",
    },
    downIcon: {
        marginLeft: 4,
    },
    filterBadge: {
        position: "absolute",
        top: 8,
        right: 8,
        width: 8,
        height: 8,
        borderRadius: 4,
        backgroundColor: "#ff3b30",
    },
    modalContainer: {
        flex: 1,
        backgroundColor: "#ffffff",
        paddingTop: 50, // Espace pour éviter le header du téléphone
        position: "absolute",
        top: 0,
        bottom: 0,
        left: 0,
        right: 0,
        zIndex: 1000,
    },
    modalContent: {
        backgroundColor: "white",
        flex: 1,
        paddingHorizontal: 16,
        paddingBottom: 30,
    },
    modalHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
    },
    modalTitle: {
        fontSize: 24,
        fontWeight: "bold",
        color: "#000",
    },
    sectionHeader: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
        marginBottom: 12,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: "500",
        color: "#000",
    },
    activitiesContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        paddingTop: 12,
        paddingBottom: 12,
    },
    activityChip: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 18,
        backgroundColor: "#f0f0f0",
        marginBottom: 8,
    },
    selectedChip: {
        backgroundColor: "#007AFF",
    },
    activityChipText: {
        fontSize: 14,
        color: "#333",
    },
    selectedChipText: {
        color: "#fff",
    },
    equipementsContainer: {
        flexDirection: "row",
        gap: 12,
        paddingTop: 12,
        paddingBottom: 12,
    },
    equipementChip: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 18,
        backgroundColor: "#f0f0f0",
        marginBottom: 8,
    },
    equipementChipText: {
        fontSize: 14,
        marginLeft: 6,
        color: "#333",
    },
    modalFooter: {
        flexDirection: "row",
        justifyContent: "space-between",
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: "#eee",
        marginTop: 16,
    },
    resetButton: {
        paddingVertical: 10,
        paddingHorizontal: 16,
    },
    resetButtonText: {
        color: "#999",
        fontSize: 16,
    },
    applyButton: {
        backgroundColor: "#007AFF",
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
    },
    applyButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
    },
});
